### ISSUE TITLE
Error building on 64-bit windows 10 machine

### ISSUE THREAD

**Issue by BCRodich** [18xx-maker/18xx-maker#436]
following error created when trying to build on Win 10 64 bit machine.  This was both before and after updating node.js to latest version.  Last log:

C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main>yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info dmg-license@1.0.8: The platform "win32" is incompatible with this module.
info "dmg-license@1.0.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.5: The platform "win32" is incompatible with this module.
info "iconv-corefoundation@1.1.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
[7/8] ⠁ electron
[-/8] ⠁ waiting...
[3/8] ⠂ node-sass
[4/8] ⠂ puppeteer
error C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\BRRODICH\\Documents\\Personal Files\\18XX\\Maker\\18xx-maker-main\\18xx-maker-main\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\BRRODICH\AppData\Local\Programs\Python\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\BRRODICH\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\BRRODICH\\Documents\\Personal Files\\18XX\\Maker\\18xx-maker-main\\18xx-maker-main\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\BRRODICH\Documents\Personal Files\18XX\Maker\18xx-maker-main\18xx-maker-main\node_modules\node-sass
gyp ERR! node -v v16.9.1

**Comment by kelsin** [comment]
Updating to `sass` instead of `node-sass` which shouldn't need binary. Can you try again on latest `main`?

**Comment by kelsin** [comment]
Everything has been updated since, If you are on a latest node you should be good now. Please let me know if not.
